{% set version = "0.1.0b1" %}
{% set name = "nanoepiseg" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "

  entry_points:
    - nanoepiseg=nanoepiseg.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.7
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.19.2
    - scipy==1.4.1
    - pandas>=1.1.3
    - meth5>=0.3.1
about:
  home: https://github.com/snajder-r/nanoepiseg
  license: MIT
  licence_url: https://opensource.org/licenses/MIT
  summary: Methylome segmentation algorithm using a changepoint detection HMM

extra:
  author: Rene Snajder
  author_email: r.snajder@dkfz-heidelberg.de
  author_url: https://github.com/snajder-r