__name__ = "nanoepiseg"
__version__ = "1.0.0b3"
__description__ = "Methylome segmentation algorithm using a changepoint detection HMM"
__url__ = "https://github.com/snajder-r/nanoepiseg"
__licence__ = "MIT"
__author__ = "Rene Snajder"
